name: Update Codewars Stats
on:
  schedule:
    - cron: "0 0 * * *"  # Обновляется каждый день

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with Codewars stats
        run: |
          curl -s https://www.codewars.com/api/v1/users/Grigoret%20Petr > codewars.json
          echo "## Codewars Stats" > README.md
          echo "\`\`\`json" >> README.md
          cat codewars.json >> README.md
          echo "\`\`\`" >> README.md
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update Codewars stats" || exit 0
          git push
